### PR TITLE
Add handling of non existing folder to file copy logic - fixes #60

### LINKED ISSUE #60: FileSystem deployment of file to non-existing directory throws exception
These test deployments ...

``` PowerShell
Deploy Test {
    By FileSystem  {
        FromSource  'test.txt'
        To 'C:\Does\Not\Exist\'
    }
}
```

and

``` PowerShell
Deploy Test {
    By FileSystem  {
        FromSource  'test.txt'
        To 'C:\Does\Not\Exist\test.txt'
    }
}
```

... both throw an exception when the destination folder does not exist, due to limitations of the Copy-Item cmdlet.

One way around the issue

``` PowerShell
Try {

    Copy-Item -Path $Map.Source -Destination $Target -Force

}
Catch [System.IO.IOException] {

    $NewDir = $Target
    if ($NewDir[-1] -ne '\')
    {
        $NewDir = Split-Path -Path $NewDir
    }
    $null = New-Item -ItemType Directory -Path $NewDir
    Copy-Item -Path $Map.Source -Destination $Target -Force

}
```

(opted for the try/catch approach to not have to do a test-path for each file)

I can go ahead and submit a pull request for this, but wanted to run it by you first in case you have reasons for not handling non-existing folders in the first place

### PR DESCRIPTION
**Pull request by csandfeld**
Went ahead and created changes in the master branch ... feel free to reject, and I will do it in dev instead

### CODE REVIEW

**Comment by RamblingCookieMonster** [comment]
Awesome!  Thanks Christian - will leave this open for a few days to see if anyone has any feedback, merge it in if nothing comes up.  Feel free to ping me if I haven't gotten around to it by Monday.

Cheers!

**Comment by csandfeld** [comment]
You're welcome Warren - happy to help

**Comment by csandfeld** [comment]
Ping ... :-)

**Comment by RamblingCookieMonster** [comment]
Alrighty, merging, thanks for the reminder (and the code)!

**Pull request merged**
