### PR TITLE
Add PowerYaml support & CopyVMFile deployment

### PR DESCRIPTION
**Pull request by DexterPOSH**
- PowerYaml replaces PSYaml, PowerYaml actively being developed by Doug Finke.
- CopyVMFile deployment type to copy files to a VM running on Server 2012 R2 Hyper-V host.
- Intialize-PSdeployment , new function which serves as a template deployment.yml file.

### CODE REVIEW

**Comment by DexterPOSH** [comment]
@RamblingCookieMonster Let me know if any feedback, this might be still be buggy.

**Comment by RamblingCookieMonster** [comment]
Awesome, thanks for submitting this!

Sorry to be a pain, but any chance we could avoid the yaml parsing changes for now? Have some work in another branch that will need some refactoring for that, would prefer to get that integrated before tackling the yaml side.

Quickest route might be to just be to [checkout all the files from latest master](http://stackoverflow.com/a/6624093/3067642) (abdb32d), apart from the following::
- PSDeploy/Initialize-PSDeployment.ps1
- PSDeploy/Invoke-PSDeployment.ps1
- PSDeploy/PSDeploy.psd1
- PSDeploy/PSDeploy.yml
- PSDeploy/PSDeployScripts/CopyVMFile.ps1
- Tests/PSDeploy.Tests.ps1
- Tests/DeploymentsCopyVMFolder.yml
- Tests/DeploymentsCopyVMFile.yml
- README.md

Alternatively, If it helps, I can create a separate branch from master, let you submit these changes to that branch, and clean out the YAML changes on my side, before integrating the rest back in.  Feel bad asking you to do that much work.

Let me know what works for you!

Thanks,

Warren

**Comment by DexterPOSH** [comment]
Hey Warren,

No worries, I can work on the above changes in the next week.
Have a long weekend coming and a short trip planned for now :smile: 

Deepak

**Comment by DexterPOSH** [comment]
Hi Warren,
I will have the changes pushed by today.

**Comment by DexterPOSH** [comment]
Oops ! 
I was pulled into a PowerShell training this week. I will soon give an update.

**Comment by DexterPOSH** [comment]
@RamblingCookieMonster , I checked out everything from the commit ( abdb32d1c4c7222254a3aa09c5e59a2392b7e36e) and added only the 9 files you mentioned on top of it.

**Comment by RamblingCookieMonster** [comment]
Manually merged into dev in 1c7090e - thanks Deepak!

**Pull request closed without merging**
