### PR TITLE
DSCPull script added

### PR DESCRIPTION
**Pull request by lucdekens**
Script to handle pushing a DSC Resource Module to a Pull server

### CODE REVIEW

**Comment by lucdekens** [comment]
DSCPull script added

**Comment by RamblingCookieMonster** [comment]
Hiyo!

Cool idea!  Added two commits (tls 1.2 / github URL issue that had nothing to do with this apart from breaking other tests, and s/tabs/spaces), but other than that, makes sense to me.

Will leave this open a day or two in case other folks have input

Thanks!

**Comment by lucdekens** [comment]
Hi Warren,
Sure, thanks.
The function is a bit rough, but it does it's work, at least for me it does
:-)
Luc

**Comment by RamblingCookieMonster** [comment]
I'm just going to forget about it if we wait : )  merging!

**Pull request merged**
