### PR TITLE
Added Git deployment

### PR DESCRIPTION
**Pull request by equelin**
This PR adds a new deployment type `Git`. The git workflow is quiet simple and can be decomposed in a few steps:
- git add 
- git commit
- git push

This PR can be seen as a RFC to see if there is any interest in this kind of deployment and also to discuss about git workflows that may differ between users.

This deployment type requires that the git command is installed and available in the PATH.

``` Powershell
Deploy Git {
    By Git Git {
        FromSource 'F:\hubic\Code\GitHub\PSDummy'
        To 'master'
        WithOptions @{
            CommitMessage = 'Automatically commited by PSDeploy'
        }
    }
}
```

`FromSource` is the local repository
`To` is the branch name
Option `CommitMessage` is the message added to each commit

### CODE REVIEW

**Comment by RamblingCookieMonster** [comment]
Awesome idea! Might be handy to include support for tags as well?

Cheers!

**Comment by equelin** [comment]
Thank you !

I've added the possibility to tag commits. Is that what you were asking for?

``` Powershell
Deploy Git {
    By Git Git {
        FromSource 'D:\GitHub\PSDummy'
        To 'Master'
        Tagged 'Prod'
        WithOptions @{
            CommitMessage = 'Automatically commited by PSDeploy'
            Tag = 'v1.0.0'
        }
    }
}
```

**Comment by RamblingCookieMonster** [comment]
Perfect!

Barring any objections, I'll merge this in later tonight; thanks for the idea and code!

**Comment by RamblingCookieMonster** [comment]
This is new, won't break existing deployments, going to merge it in.  If anyone has other suggestions, feel free to open a new issue or re-open this!  Thanks again @equelin!

Edit:  @equelin just noticed this is on the dev branch.  I've been bad.  Would you mind submitting to the master branch?

**Pull request merged**
